version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: magical-board-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://magical_user:magical_pass@postgres:5432/magical_board
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-secret-key-here-change-in-production
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - magical-network

  postgres:
    image: postgres:16-alpine
    container_name: magical-board-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=magical_user
      - POSTGRES_PASSWORD=magical_pass
      - POSTGRES_DB=magical_board
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U magical_user -d magical_board"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - magical-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: magical-board-pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@magical-board.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgres
    networks:
      - magical-network

volumes:
  postgres_data:

networks:
  magical-network:
    driver: bridge